---
deployment:
  tasks:
    - set -euxo pipefail
    - export SRC="$PWD"                 # <— root of repo
    - export DEPLOY_PATH="/home/abissneti/public_html"
    - /bin/mkdir -p "$DEPLOY_PATH"
    - |
      if command -v rsync >/dev/null 2>&1; then
        "$(command -v rsync)" -a --delete --info=stats2 \
          --exclude="/.git" --exclude="/node_modules" --exclude="/.env" \
          "$SRC"/ "$DEPLOY_PATH"/
      else
        echo "rsync not found; using cp fallback"
        shopt -s dotglob extglob
        mkdir -p "$DEPLOY_PATH/.well-known"
        for p in "$DEPLOY_PATH"/!(.well-known); do rm -rf "$p"; done
        cp -a "$SRC"/. "$DEPLOY_PATH"/
      fi
    - '[ -f "$DEPLOY_PATH/.htaccess" ] || printf "%s\n" "Options -Indexes" > "$DEPLOY_PATH/.htaccess"'
